"""Add parent_message_id to messages for reply threading

Revision ID: 03b4c37338dd
Revises: 7ec112df470d
Create Date: 2025-11-17 15:51:17.066293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b4c37338dd'
down_revision = '7ec112df470d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_message_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'messages', ['parent_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_message_id')

    # ### end Alembic commands ###
