"""empty message

Revision ID: 5e2796a142e9
Revises: f9b1c3a7d2b1
Create Date: 2025-11-17 08:39:39.091389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2796a142e9'
down_revision = 'f9b1c3a7d2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_name', sa.String(length=200), nullable=True))
        batch_op.alter_column('requester_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('requester_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('requester_name')

    # ### end Alembic commands ###
