"""add testing table

Revision ID: 6500c2dfc28c
Revises: fc83ba3f8f31
Create Date: 2025-11-19 08:47:02.552744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6500c2dfc28c'
down_revision = 'fc83ba3f8f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('test_type', sa.String(length=50), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testing', schema=None) as batch_op:
        batch_op.create_index('ix_testing_status', ['status'], unique=False)
        batch_op.create_index('ix_testing_ticket_id', ['ticket_id'], unique=False)
        batch_op.create_index('ix_testing_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing', schema=None) as batch_op:
        batch_op.drop_index('ix_testing_user_id')
        batch_op.drop_index('ix_testing_ticket_id')
        batch_op.drop_index('ix_testing_status')

    op.drop_table('testing')
    # ### end Alembic commands ###
