"""Add status_changed_at to tickets

Revision ID: a8caf06493d2
Revises: bbe87cf95669
Create Date: 2025-11-17 10:03:30.625361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8caf06493d2'
down_revision = 'bbe87cf95669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('status_changed_at')

    # ### end Alembic commands ###
