"""autogenerate after import fix

Revision ID: e65e93654cf0
Revises: 
Create Date: 2025-11-15 11:05:48.544810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'e65e93654cf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to avoid duplicate table errors ###

    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # tags
    if 'tags' not in existing_tables:
        op.create_table(
            'tags',
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('color', sa.String(length=7), nullable=True),
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )

    # users
    if 'users' not in existing_tables:
        op.create_table(
            'users',
            sa.Column('email', sa.String(length=120), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=True),
            sa.Column('password_hash', sa.String(length=255), nullable=True),
            sa.Column('role', sa.String(length=20), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email')
        )

    # kb_articles
    if 'kb_articles' not in existing_tables:
        op.create_table(
            'kb_articles',
            sa.Column('title', sa.String(length=200), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('author_id', sa.UUID(), nullable=False),
            sa.Column('views', sa.Integer(), nullable=True),
            sa.Column('is_public', sa.Boolean(), nullable=True),
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # tickets
    if 'tickets' not in existing_tables:
        op.create_table(
            'tickets',
            sa.Column('ticket_id', sa.String(length=20), nullable=False),
            sa.Column('subject', sa.String(length=200), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('priority', sa.String(length=20), nullable=True),
            sa.Column('requester_id', sa.UUID(), nullable=False),
            sa.Column('assignee_id', sa.UUID(), nullable=True),
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('ticket_id')
        )

        # create indexes only if we just created tickets table
        with op.batch_alter_table('tickets', schema=None) as batch_op:
            batch_op.create_index('ix_tickets_created', ['created_at'], unique=False)
            batch_op.create_index('ix_tickets_priority', ['priority'], unique=False)
            batch_op.create_index('ix_tickets_status', ['status'], unique=False)

    # article_tags
    if 'article_tags' not in existing_tables:
        op.create_table(
            'article_tags',
            sa.Column('article_id', sa.UUID(), nullable=False),
            sa.Column('tag_id', sa.UUID(), nullable=False),
            sa.ForeignKeyConstraint(['article_id'], ['kb_articles.id'], ),
            sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
            sa.PrimaryKeyConstraint('article_id', 'tag_id')
        )

    # attachments
    if 'attachments' not in existing_tables:
        op.create_table(
            'attachments',
            sa.Column('filename', sa.String(length=255), nullable=False),
            sa.Column('url', sa.String(length=500), nullable=False),
            sa.Column('type', sa.String(length=20), nullable=True),
            sa.Column('size', sa.Integer(), nullable=True),
            sa.Column('ticket_id', sa.UUID(), nullable=False),
            sa.Column('uploaded_by', sa.UUID(), nullable=False),
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
            sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # comments
    if 'comments' not in existing_tables:
        op.create_table(
            'comments',
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('ticket_id', sa.UUID(), nullable=False),
            sa.Column('author_id', sa.UUID(), nullable=False),
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted to be safe ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'comments' in existing_tables:
        op.drop_table('comments')

    if 'attachments' in existing_tables:
        op.drop_table('attachments')

    if 'article_tags' in existing_tables:
        op.drop_table('article_tags')

    if 'tickets' in existing_tables:
        with op.batch_alter_table('tickets', schema=None) as batch_op:
            # drop indexes only if they exist; if this ever errors, you can remove these lines
            batch_op.drop_index('ix_tickets_status')
            batch_op.drop_index('ix_tickets_priority')
            batch_op.drop_index('ix_tickets_created')
        op.drop_table('tickets')

    if 'kb_articles' in existing_tables:
        op.drop_table('kb_articles')

    if 'users' in existing_tables:
        op.drop_table('users')

    if 'tags' in existing_tables:
        op.drop_table('tags')
    # ### end Alembic commands ###

