"""Add security question fields to users table

Revision ID: fc83ba3f8f31
Revises: 03b4c37338dd
Create Date: 2025-11-18 08:36:55.970759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc83ba3f8f31'
down_revision = '03b4c37338dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('security_answer_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_answer_hash')
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###
